p8105_hw3_yz4433
================
Yifei Zhao
2022-10-13

## Problem 1

### description of data

``` r
data("instacart")

instacart = 
  instacart %>% 
  as_tibble(instacart)
```

This dataset contains 1384617 rows and 15 columns, with each row
resprenting a single product from an instacart order. Variables include
identifiers for user, order, and product; the order in which each
product was added to the cart. There are several order-level variables,
describing the day and time of the order, and number of days since prior
order. Then there are several item-specific variables, describing the
product name (e.g. Yogurt, Avocado), department (e.g. dairy and eggs,
produce), and aisle (e.g. yogurt, fresh fruits), and whether the item
has been ordered by this user in the past. In total, there are 39123
products found in 131209 orders from 131209 distinct users.

``` r
instacart %>% 
  count(aisle) %>% 
  arrange(desc(n))
```

    ## # A tibble: 134 × 2
    ##    aisle                              n
    ##    <chr>                          <int>
    ##  1 fresh vegetables              150609
    ##  2 fresh fruits                  150473
    ##  3 packaged vegetables fruits     78493
    ##  4 yogurt                         55240
    ##  5 packaged cheese                41699
    ##  6 water seltzer sparkling water  36617
    ##  7 milk                           32644
    ##  8 chips pretzels                 31269
    ##  9 soy lactosefree                26240
    ## 10 bread                          23635
    ## # … with 124 more rows

In total, there are 134 aisles, with fresh vegetables and fresh fruits
holding the most items ordered by far.

### plot of items

``` r
instacart %>% 
  count(aisle) %>% 
  filter(n > 10000) %>% 
  mutate(aisle = fct_reorder(aisle, n)) %>% 
  ggplot(aes(x = aisle, y = n)) + 
  geom_point() + 
  labs(title = "Number of items ordered in each aisle") +
  theme(axis.text.x = element_text(angle = 60, hjust = 1))
```

![](p8105_hw3_yz4433_files/figure-gfm/unnamed-chunk-3-1.png)<!-- -->

### table of three most popular items

``` r
instacart %>% 
  filter(aisle %in% c("baking ingredients", "dog food care", "packaged vegetables fruits")) %>%
  group_by(aisle) %>% 
  count(product_name) %>% 
  mutate(rank = min_rank(desc(n))) %>% 
  filter(rank < 4) %>% 
  arrange(desc(n)) %>%
  knitr::kable()
```

| aisle                      | product_name                                  |    n | rank |
|:---------------------------|:----------------------------------------------|-----:|-----:|
| packaged vegetables fruits | Organic Baby Spinach                          | 9784 |    1 |
| packaged vegetables fruits | Organic Raspberries                           | 5546 |    2 |
| packaged vegetables fruits | Organic Blueberries                           | 4966 |    3 |
| baking ingredients         | Light Brown Sugar                             |  499 |    1 |
| baking ingredients         | Pure Baking Soda                              |  387 |    2 |
| baking ingredients         | Cane Sugar                                    |  336 |    3 |
| dog food care              | Snack Sticks Chicken & Rice Recipe Dog Treats |   30 |    1 |
| dog food care              | Organix Chicken & Brown Rice Recipe           |   28 |    2 |
| dog food care              | Small Dog Biscuits                            |   26 |    3 |

### table of Pink Lady Apples and Coffee Ice Cream mean ordered hour

``` r
instacart %>%
  filter(product_name %in% c("Pink Lady Apples", "Coffee Ice Cream")) %>%
  group_by(product_name, order_dow) %>%
  summarize(mean_hour = mean(order_hour_of_day)) %>%
  spread(key = order_dow, value = mean_hour) %>%
  knitr::kable(digits = 2)
```

    ## `summarise()` has grouped output by 'product_name'. You can override using the
    ## `.groups` argument.

| product_name     |     0 |     1 |     2 |     3 |     4 |     5 |     6 |
|:-----------------|------:|------:|------:|------:|------:|------:|------:|
| Coffee Ice Cream | 13.77 | 14.32 | 15.38 | 15.32 | 15.22 | 12.26 | 13.83 |
| Pink Lady Apples | 13.44 | 11.36 | 11.70 | 14.25 | 11.55 | 12.78 | 11.94 |

## Problem 2

### Manipulate data

``` r
data_acc = read_csv(file = "./data/accel_data.csv", show_col_types = FALSE) %>% 
  janitor::clean_names() %>% 
  add_column(group = "days", .after = "day") %>% 
  mutate(group = ifelse((day == "Saturday" | day == "Sunday"), 'weekend', 'weekday'))
```

The final 35 $\times$ 1444 dataset, data_acc, illustrates activity
counts for each minute of a 24-hour day starting at midnight of 35 days
in 5 weeks. Parts of counts values are 1 and the dataset includes a
weekday vs weekend variable.

### Table showing totals

``` r
data_acc = data_acc %>%
  add_column(total = rowSums(data_acc[,5:1444]), .after = "group")
knitr::kable(data_acc[, 1:5], "simple")
```

| week | day_id | day       | group   |     total |
|-----:|-------:|:----------|:--------|----------:|
|    1 |      1 | Friday    | weekday | 480542.62 |
|    1 |      2 | Monday    | weekday |  78828.07 |
|    1 |      3 | Saturday  | weekend | 376254.00 |
|    1 |      4 | Sunday    | weekend | 631105.00 |
|    1 |      5 | Thursday  | weekday | 355923.64 |
|    1 |      6 | Tuesday   | weekday | 307094.24 |
|    1 |      7 | Wednesday | weekday | 340115.01 |
|    2 |      8 | Friday    | weekday | 568839.00 |
|    2 |      9 | Monday    | weekday | 295431.00 |
|    2 |     10 | Saturday  | weekend | 607175.00 |
|    2 |     11 | Sunday    | weekend | 422018.00 |
|    2 |     12 | Thursday  | weekday | 474048.00 |
|    2 |     13 | Tuesday   | weekday | 423245.00 |
|    2 |     14 | Wednesday | weekday | 440962.00 |
|    3 |     15 | Friday    | weekday | 467420.00 |
|    3 |     16 | Monday    | weekday | 685910.00 |
|    3 |     17 | Saturday  | weekend | 382928.00 |
|    3 |     18 | Sunday    | weekend | 467052.00 |
|    3 |     19 | Thursday  | weekday | 371230.00 |
|    3 |     20 | Tuesday   | weekday | 381507.00 |
|    3 |     21 | Wednesday | weekday | 468869.00 |
|    4 |     22 | Friday    | weekday | 154049.00 |
|    4 |     23 | Monday    | weekday | 409450.00 |
|    4 |     24 | Saturday  | weekend |   1440.00 |
|    4 |     25 | Sunday    | weekend | 260617.00 |
|    4 |     26 | Thursday  | weekday | 340291.00 |
|    4 |     27 | Tuesday   | weekday | 319568.00 |
|    4 |     28 | Wednesday | weekday | 434460.00 |
|    5 |     29 | Friday    | weekday | 620860.00 |
|    5 |     30 | Monday    | weekday | 389080.00 |
|    5 |     31 | Saturday  | weekend |   1440.00 |
|    5 |     32 | Sunday    | weekend | 138421.00 |
|    5 |     33 | Thursday  | weekday | 549658.00 |
|    5 |     34 | Tuesday   | weekday | 367824.00 |
|    5 |     35 | Wednesday | weekday | 445366.00 |

According to the table, we find the maximum is 6.8591^{5} and the
minimum is 1440, but no apparent trends relating to weekdays or weekends
(certain days in general week).

### Activity plot

``` r
data_acc = data_acc[,-5] %>% 
  pivot_longer(
    activity_1:activity_1440,
    names_to = "activity", 
    values_to = "act_counts") %>%
  mutate(activity = as.integer(substr(activity, 10, 13)))
```

``` r
ggplot(data_acc, aes(x = activity, y = act_counts)) + 
  geom_point(aes(color = day), size = 1, alpha = 0.5) +
  ggtitle("24-hour activity time courses for each day") +
  xlab('activity time in minute') +
  scale_x_continuous(breaks = seq(0, 1440, 60)) +
  theme(axis.text.x = element_text(angle = 90))
```

![](p8105_hw3_yz4433_files/figure-gfm/unnamed-chunk-9-1.png)<!-- -->

From the activity plot, the data have several peaks and troughs.
Overall, Monday high Wednesday low. There are two main peak areas,
activity time points lie in (570,750) and (1170,1320), and the main
trough area is about (60,240). The results are strongly relating to
people’s daily life (low activity when sleep, high when work or study).

## Problem 3

### Data cleaning

``` r
data("ny_noaa")
ny_noaa = ny_noaa %>% 
  janitor::clean_names() %>% 
  separate(date, into = c("year", "month", "day")) %>% 
  mutate(prcp = as.numeric(prcp)/10, tmax = as.numeric(tmax)/10, tmin = as.numeric(tmin)/10, snow = as.numeric(snow))
```

``` r
getmode <- function(v) {
   uniqv <- unique(v)
   uniqv[which.max(tabulate(match(v, uniqv)))]
}
```

We divide the prcp, tmax, and tmin values by 10 to get the real
precipitation and temperature values. The mode of snowfall value is 0.
The reason could be that temperatures and precipitation of the data
imply not strong conditions of snowfall in most cases.

### temperature plot

#### Jan and July data

``` r
janmax =
  ny_noaa %>%
  drop_na(tmax) %>%
  filter(month == "01")
df_jan = aggregate(tmax ~ id+year, janmax, mean)

julmax =
  ny_noaa %>%
  drop_na(tmax) %>%
  filter(month == "07")
df_jul = aggregate(tmax ~ id+year, julmax, mean)
```

#### plotting

``` r
tmaxjan = 
  df_jan %>% 
  ggplot(aes(x = year, y = tmax, color = id, group = id)) + 
  ggtitle(" Average max temperature in January") +
  geom_point(size = 1, alpha = .5) +
  geom_line() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  theme(legend.position = "none")
```

``` r
tmaxjul = 
  df_jul %>% 
  ggplot(aes(x = year, y = tmax, color = id,  group = id)) + 
  ggtitle(" Average max temperature in July") +
  geom_point(size = 1, alpha = .5) +
  geom_line() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  theme(legend.position = "none")

tmaxjan/tmaxjul
```

![](p8105_hw3_yz4433_files/figure-gfm/unnamed-chunk-14-1.png)<!-- -->

According to the year-tmax 2-panel plot, the max temperatures in January
fluctuate greatly, and these two subplots are of the similar trends
(correspondingly reach the peaks and troughs), which implies the
seasonal or yearly weather simultaneously influence the near dates. Both
of the data have outliers. For example, the lowest point in Jan 1982 and
the lowest point in Jul 1988.

### tmax vs tmin, and snowfall plotting

``` r
ny_temp = 
  ny_noaa %>% 
  drop_na(tmax) %>% 
  drop_na(tmin) %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  ggtitle("tmax vs tmin") +
  geom_hex(alpha = .5) +
  theme(legend.position = "bottom", legend.key.size = unit(30, "pt"))
  # theme(axis.text.x=element_blank())
  # theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

``` r
ny_snow =
  ny_noaa %>%
  filter(snow > 0 & snow < 100) %>% 
  ggplot(aes(x = snow, color = year)) +
  ggtitle("distribution of snowfall values") +
  geom_density(alpha = .5) + 
  viridis::scale_fill_viridis(discrete = TRUE) +
  theme(legend.position = "bottom", legend.key.size = unit(6, "pt"))
  # theme(axis.text.x=element_blank())
  # theme(axis.text.x = element_text(angle = 90, hjust = 1))

ny_temp + ny_snow
```

![](p8105_hw3_yz4433_files/figure-gfm/unnamed-chunk-16-1.png)<!-- -->
