---
title: "p8105_hw3_yz4433"
author: "Yifei Zhao"
date: "2022-10-13"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(stringr)
```

## Problem 2
### Manipulate data
```{r}
data_acc = read_csv(file = "./data/accel_data.csv") %>% 
  janitor::clean_names() %>% 
  add_column(group = "days", .after = "day") %>% 
  mutate(group = ifelse((day == "Saturday" | day == "Sunday"), 'weekend', 'weekday'))
```

### Table showing totals
```{r}
data_acc = data_acc %>%
  add_column(total = rowSums(data_acc[,5:50]), .after = "group")
knitr::kable(data_acc[, 1:5], "simple")
```

```{r}
data_acc = data_acc[,-5] %>% 
  pivot_longer(
    activity_1:activity_1440,
    names_to = "activity", 
    values_to = "act_counts") %>%
  mutate(activity = as.integer(substr(activity, 10, 13)))
```

### Activity plot
```{r}
ggplot(data_acc, aes(x = activity, y = act_counts)) + 
  geom_point(aes(color = day), size = 1, alpha = 0.5) +
  scale_x_continuous(breaks = seq(0, 1440, 60)) +
  theme(axis.text.x = element_text(angle = 90))
```

## Problem 3
```{r}
library(p8105.datasets)
library(patchwork)
data("ny_noaa")
```

### Data cleaning
```{r}
ny_noaa = ny_noaa %>% 
  janitor::clean_names() %>% 
  separate(date, into = c("year", "month", "day")) %>% 
  mutate(prcp = as.numeric(prcp)/10, tmax = as.numeric(tmax)/10, tmin = as.numeric(tmin)/10, snow = as.numeric(snow))
```

### temperature plot
#### Jan and July data
```{r}
janmax =
  ny_noaa %>%
  drop_na(tmax) %>%
  filter(month == "01")
df_jan = aggregate(tmax ~ id+year, janmax, mean)

julmax =
  ny_noaa %>%
  drop_na(tmax) %>%
  filter(month == "07")
df_jul = aggregate(tmax ~ id+year, julmax, mean)
```

#### plotting
```{r}
tmaxjan = 
  df_jan %>% 
  ggplot(aes(x = year, y = tmax, color = id, group = id)) + 
  geom_point(size = 1, alpha = .5) +
  geom_line() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  theme(legend.position = "none")
```

```{r}
tmaxjul = 
  df_jul %>% 
  ggplot(aes(x = year, y = tmax, color = id,  group = id)) + 
  geom_point(size = 1, alpha = .5) +
  geom_line() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  theme(legend.position = "none")

tmaxjan/tmaxjul
```

### tmax vs tmin, and snowfall plotting
```{r}
ny_temp = 
  ny_noaa %>% 
  drop_na(tmax) %>% 
  drop_na(tmin) %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = year), alpha = .5) +
  theme(legend.position = "bottom", legend.key.size = unit(5, "pt")) +
  # theme(axis.text.x=element_blank())
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

```{r}
ny_snow =
  ny_noaa %>%
  filter(snow > 0 & snow < 100) %>% 
  ggplot(aes(x = snow, color = year)) +
  geom_density(alpha = .5) + 
  viridis::scale_fill_viridis(discrete = TRUE) +
  theme(legend.position = "bottom", legend.key.size = unit(5, "pt")) +
  # theme(axis.text.x=element_blank())
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

ny_temp + ny_snow
```